version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: oddo-approver-db
    environment:
      POSTGRES_DB: oddo_approver
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js Application
  web:
    build: .
    container_name: oddo-approver-web
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/oddo_approver?schema=public
      NEXTAUTH_SECRET: your-secret-key-here
      NEXTAUTH_URL: http://localhost:3000
      EXCHANGE_RATE_API_URL: https://api.exchangerate.host/convert
      NEXT_PUBLIC_APP_NAME: Oddo Approver
      NEXT_PUBLIC_COMPANY_NAME: OddoCorp
      NEXT_PUBLIC_DEFAULT_CURRENCY: USD
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma db push && npx prisma db seed && npm run dev"

volumes:
  postgres_data:
